import { CONTACT_EMAIL, LEGAL_NAME, TERMS_VERSION } from "@/lib/site";

export default function Terms() {
  return <main className="legal-page">
    <h1>Términos y Condiciones</h1>
    <p className="legal-meta">Versión {TERMS_VERSION}</p>
    <p>Estos Términos regulan el acceso y uso de SECOND VOW, operado por <strong>{LEGAL_NAME}</strong>. Contacto: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. Al crear una cuenta o utilizar funciones reservadas aceptas estas reglas y la versión registrada para cada operación.</p>

    <h2>1. Naturaleza del servicio</h2>
    <p>SECOND VOW es un marketplace tecnológico especializado en vestidos de novia usados y en vestidos nuevos que no fueron utilizados por su propietaria. SECOND VOW no adquiere la propiedad ni se convierte en vendedor del artículo. La compraventa se celebra entre compradora y vendedora; SECOND VOW presta servicios de publicación, comunicación, moderación, pago, reputación, seguimiento y gestión de incidencias. SECOND VOW responde por sus propias obligaciones como proveedor de la plataforma, sin excluir derechos irrenunciables previstos en la legislación mexicana.</p>

    <h2>2. Capacidad y cuenta</h2>
    <p>Las usuarias deben ser mayores de edad y contar con capacidad legal para contratar. La información proporcionada debe ser veraz y mantenerse actualizada. SECOND VOW está destinado exclusivamente a ventas ocasionales del vestido propio por falta de uso, cambio de planes, celebración concluida u otra causa semejante. Se prohíbe usarlo para inventario comercial, reventa habitual o actividad profesional. SECOND VOW podrá solicitar aclaraciones, limitar publicaciones o cerrar cuentas cuando detecte habitualidad. La declaración de una usuaria no impide la aplicación de la legislación que corresponda por la realidad de sus actividades.</p>

    <h2>3. Obligaciones de la vendedora</h2>
    <p>Al enviar un vestido a revisión, la vendedora declara que es propietaria o está autorizada para venderlo; que es auténtico y de procedencia lícita; que las fotografías corresponden al artículo; y que informó con veracidad marca, medidas, modificaciones, condición, daños, accesorios y demás características relevantes. Debe conservar evidencia razonable del vestido, empaque y entrega a paquetería.</p>
    <p>La vendedora concede a SECOND VOW una licencia no exclusiva y temporal para alojar, adaptar técnicamente, mostrar y promocionar las fotografías y textos de la publicación mientras sea necesario para operar la plataforma y documentar una transacción o controversia.</p>
    <p>La vendedora deberá cooperar en cualquier aclaración sobre propiedad, autenticidad, procedencia o derechos sobre las fotografías. Responderá frente a la compradora y terceros por información falsa, artículos ilícitos o infracciones que le sean atribuibles, y mantendrá a SECOND VOW indemne respecto de reclamaciones originadas por su conducta, sin excluir responsabilidad propia de la plataforma ni derechos irrenunciables.</p>

    <h2>4. Autenticidad, marcas y contenido prohibido</h2>
    <p>Las marcas pertenecen a sus titulares y su mención no implica afiliación. Se prohíben artículos ilícitos, robados o falsificados; fotografías sin autorización; descripciones engañosas; ocultamiento de daños; suplantación; acoso; spam; fraude; manipulación de precios y uso de la plataforma para evadir deliberadamente comisiones o mecanismos de seguridad. SECOND VOW puede pedir evidencia, retirar publicaciones y colaborar con autoridades.</p>

    <h2>5. Ofertas, pedido y disponibilidad</h2>
    <p>La compradora puede conversar y preguntar por el precio, pero solo la vendedora emite la oferta formal. La oferta incluye el precio definitivo del vestido y un costo de envío fijo calculado con el código postal de la compradora. No hay contraofertas. La compradora puede aceptarla o rechazarla; la vendedora puede cancelarla mientras siga pendiente.</p>
    <p>La oferta vence en 48 horas. Al aceptarla se genera un pedido con hasta 48 horas para pagar. Puede reintentar Stripe dentro de ese plazo; cada sesión de Checkout dura aproximadamente 60 minutos. Ni aceptar ni abrir Checkout oculta la publicación. La primera compradora cuyo pago sea confirmado obtiene el vestido; los demás pedidos se cancelan y cualquier segundo cargo excepcional se revisa y reembolsa.</p>
    <p>Antes de la oferta, la compradora comparte de forma privada en la conversación su nombre completo y el domicilio o sucursal de paquetería donde recibirá. La vendedora utiliza ese destino para calcular el envío asegurado. Al aceptar la oferta, el destino queda vinculado al pedido y ya no puede modificarse unilateralmente.</p>

    <h2>6. Precio y comisión</h2>
    <p>Publicar es gratuito. En una venta concluida, SECOND VOW retiene <strong>18% del total de la oferta: vestido más envío</strong>. Esa comisión contempla el costo ordinario de Stripe; no se agrega otro cargo administrativo fijo. La vendedora recibe el 82% del total y de ese saldo paga la guía.</p>
    <p>SECOND VOW está destinada a ventas ocasionales de vestidos y accesorios de propiedad personal, usados o nuevos que no hayan sido utilizados. La realización de una venta aislada no implica que SECOND VOW considere automáticamente a la vendedora como comerciante, proveedora o persona que realiza una actividad empresarial. Cada usuaria será responsable de determinar las consecuencias fiscales que, en su caso, correspondan a su situación particular.</p>
    <p>SECOND VOW emitirá, cuando legalmente corresponda, el comprobante fiscal relativo a la comisión o a los servicios que cobre directamente. Solo solicitará RFC u otros datos fiscales, informará operaciones, efectuará retenciones o emitirá constancias cuando exista una obligación legal aplicable a la operación o a la situación de la usuaria. La declaración de una venta como ocasional no prevalecerá si la frecuencia, volumen, inventario, adquisición para reventa u otras circunstancias demuestran razonablemente una actividad comercial o profesional; en ese caso SECOND VOW podrá restringir la cuenta. Esta cláusula no constituye asesoría fiscal individual.</p>

    <h2>7. Pagos, saldo y retiros</h2>
    <p>Los pagos se procesan mediante Stripe u otro proveedor habilitado. SECOND VOW no conserva números completos de tarjeta ni credenciales bancarias completas. El saldo de la vendedora permanece retenido durante el envío y la ventana de reclamación. Si no existe reclamación activa y termina el periodo de protección, el saldo puede liberarse para retiro a la cuenta bancaria vinculada.</p>
    <p>Un pago recibido después de vencer o liberarse una reserva no autoriza automáticamente el envío: se coloca en revisión para confirmar disponibilidad o tramitar reembolso. SECOND VOW puede pausar saldos ante fraude, devolución, reclamación, contracargo, orden de autoridad o error de procesamiento.</p>

    <h2>8. Envío</h2>
    <p>SECOND VOW no ofrece pruebas ni entregas presenciales. La vendedora contrata una paquetería reconocida con rastreo y seguro, registra empresa y guía dentro de cinco días naturales desde el pago y embala adecuadamente el vestido. Todo envío deberá contar con rastreo, seguro, firma y entrega contra identificación oficial. La vendedora deberá contratar un servicio que permita acreditar la recepción por la compradora o por la persona autorizada en el destino del pedido. Si el pago está en revisión, no debe enviar.</p>
    <p>Ambas partes deberán documentar razonablemente la operación. La vendedora conservará fotografías del estado del vestido, su empaquetado, paquete cerrado y entrega a paquetería; el video es especialmente recomendable. La compradora conservará fotografías del paquete cerrado y video continuo de su apertura y revisión. La ausencia de evidencia no determina automáticamente una controversia, pero podrá considerarse al evaluar hechos que no puedan acreditarse por otros medios.</p>
    <h2>8.1 Fotografías y promoción</h2><p>La vendedora concede la licencia necesaria para mostrar las fotografías en la publicación y operar el marketplace. El uso adicional en redes sociales o publicidad requiere una autorización opcional y separada al publicar; puede retirarse para usos futuros, sin afectar materiales difundidos lícitamente ni evidencia que deba conservarse.</p>

    <h2>9. Recepción y reclamaciones</h2>
    <p>SECOND VOW puede conocer la entrega mediante un evento <em>delivered</em> recibido del proveedor de rastreo o mediante la confirmación manual de la compradora. Dispone de <strong>48 horas desde que SECOND VOW recibe y registra la primera confirmación válida de entrega</strong> para reportar que el paquete no fue recibido, información falsa o materialmente incorrecta, incluido daño relevante no informado. La fecha histórica del transportista se conserva como evidencia, pero no reduce retroactivamente la ventana. Sin reclamación oportuna opera la aceptación automática interna.</p>
    <p><strong>No procede una devolución porque el vestido no quede, no favorezca, la talla elegida sea inadecuada, exista cambio de opinión o se encuentre otra opción.</strong></p>
    <p>SECOND VOW puede solicitar fotografías, video, medidas, etiquetas, empaque, comunicaciones y seguimiento. El plazo operativo de la plataforma no limita derechos que legalmente resulten irrenunciables.</p>
    <p>SECOND VOW resolverá considerando toda la evidencia disponible. Si la paquetería reporta entrega y la compradora manifiesta oportunamente que no recibió el paquete, el saldo permanecerá bloqueado mientras se revisan el rastreo, la firma, el nombre de quien recibió y la constancia de entrega disponible. La evidencia incompleta puede dificultar acreditar el estado, embalaje, recepción o apertura. Un video continuo y contemporáneo tendrá mayor valor probatorio interno que uno editado, interrumpido o grabado posteriormente. La constancia de paquetería acredita la entrega, pero no necesariamente el estado interior. La entrega contra identificación no elimina el derecho a reclamar falta de recepción, información falsa o daño relevante no informado.</p>

    <h2>10. Devoluciones y reembolsos</h2>
    <p>Una devolución solo puede autorizarse por información falsa o materialmente incorrecta. La compradora debe subir una guía rastreable, entregarla a paquetería dentro del plazo comunicado y conservar el vestido sustancialmente en el estado recibido. El seguimiento puede acreditar la recepción aunque la vendedora no la confirme. Cuando la causa sea atribuible a la vendedora, podrá cargarse el costo real comprobable de la guía y un costo logístico previamente informado; no se aplican multas automáticas.</p>

    <h2>11. Cancelaciones, falta de envío y contracargos</h2>
    <p>La vendedora puede cancelar unilateralmente mientras el vestido no haya sido enviado. Antes del pago se cancela el pedido; durante el Checkout se intenta cerrar la sesión de Stripe; después del pago y antes del envío se bloquea la guía y se solicita un reembolso completo al medio de pago original. El vestido vuelve a publicarse cuando Stripe confirma el reembolso. Una vez enviado, la vendedora ya no puede cancelar unilateralmente.</p>
    <p>Si la vendedora no registra una guía dentro de cinco días naturales, el sistema bloquea el envío tardío, coloca la operación en reembolso pendiente y mantiene el saldo bloqueado hasta que Stripe confirme el reembolso. Si Stripe Radar abre una revisión, emite una alerta temprana de fraude o la compradora desconoce el cargo, SECOND VOW bloquea envío y retiro y muestra a la vendedora “NO ENVÍES”. Una alerta es una medida preventiva y no constituye por sí sola una declaración de fraude. La aceptación automática de 48 horas no impide un contracargo bancario posterior.</p>

    <h2>12. Moderación, seguridad y pagos externos</h2>
    <p>SECOND VOW puede aprobar, pedir cambios, rechazar, archivar o retirar publicaciones y limitar cuentas ante reportes fundados, falsificación, fraude o riesgos de seguridad. La moderación no constituye certificación absoluta de autenticidad o calidad. Los pagos y acuerdos efectuados fuera de SECOND VOW carecen de la trazabilidad y protección operativa de la plataforma.</p>

    <h2>13. Propiedad intelectual y avisos</h2>
    <p>El nombre, interfaz, software y contenidos propios de SECOND VOW están protegidos. Una persona titular puede reportar material presuntamente infractor al correo de contacto, identificando sus datos, el derecho invocado, la publicación, la ubicación del contenido y evidencia razonable de titularidad. SECOND VOW acusará recibo, podrá ocultar preventivamente el contenido, notificará a la usuaria que lo publicó y evaluará cualquier respuesta. Podrá retirar definitivamente el contenido cuando exista evidencia suficiente, reiteración, orden de autoridad o falta de respuesta. Las declaraciones deliberadamente falsas podrán ocasionar suspensión y responsabilidad de quien las formula.</p>

    <h2>14. Datos personales</h2>
    <p>El tratamiento de datos se rige por el Aviso de Privacidad vigente. La aceptación de estos Términos no sustituye consentimientos específicos legalmente necesarios.</p>

    <h2>15. Cambios, ley y autoridades</h2>
    <p>La fecha y versión vigentes aparecen al inicio. SECOND VOW puede actualizarlos y comunicarlos mediante la página, correo o aviso visible dentro de la cuenta. La mera publicación podrá informar cambios no materiales; los cambios que afecten sustancialmente una operación futura requerirán una nueva aceptación cuando legalmente corresponda. Cada compra conserva la versión y evidencia de aceptación aplicables al momento de pagar.</p>
    <p>Estos Términos se interpretan conforme a las leyes de México. Para controversias que legalmente puedan someterse a convenio, las partes se someten a los tribunales competentes de Guadalajara, Jalisco. Permanecen a salvo la competencia de PROFECO, las autoridades de protección de datos, los derechos irrenunciables y cualquier fuero que legalmente corresponda a una consumidora.</p>
  </main>;
}
