"use client";
import Link from "next/link";import {useMemo,useState} from "react";import {createClient} from "@/lib/supabase/client";import {useRouter} from "next/navigation";
function csvDownload(name:string,rows:any[]){if(!rows.length)return;const keys=Array.from(new Set(rows.flatMap(r=>Object.keys(r))));const esc=(v:any)=>`"${String(v??"").replaceAll('"','""')}"`;const csv=[keys.map(esc).join(','),...rows.map(r=>keys.map(k=>esc(r[k])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
export default function AdminDashboard(p:{verifications:any[];claims:any[];brands:any[];suggestions:any[];users:any[];reports:any[];arco:any[];orders:any[];payments:any[];shipments:any[]}){const supabase=useMemo(()=>createClient(),[]);const router=useRouter();const[link,setLink]=useState<Record<string,string>>({});const refresh=()=>router.refresh();async function verify(id:string,status:string){const{error}=await supabase.rpc("admin_resolve_identity_verification",{p_verification_id:id,p_status:status});error?alert(error.message):refresh()}async function brand(id:string,action:string){const{error}=await supabase.rpc("admin_resolve_brand_suggestion",{p_suggestion_id:id,p_action:action,p_existing_brand_id:action==='link_existing'?(link[id]||null):null,p_notes:null});error?alert(error.message):refresh()}async function block(u:any){const reason=u.is_blocked?null:(prompt('Motivo del bloqueo')||'Incumplimiento de reglas');const{error}=await supabase.rpc('admin_set_user_blocked',{p_user_id:u.id,p_blocked:!u.is_blocked,p_reason:reason});error?alert(error.message):refresh()}async function arcoAction(id:string,status:string){const response=prompt('Respuesta administrativa (opcional)')||null;const{error}=await supabase.from('arco_requests').update({status,admin_response:response,resolved_at:status==='resolved'?new Date().toISOString():null}).eq('id',id);error?alert(error.message):refresh()}async function reportAction(id:string,status:string){const{error}=await supabase.from('conversation_reports').update({status}).eq('id',id);error?alert(error.message):refresh()}async function claim(id:string,status:string){const{error}=status==='approved_return'?await supabase.rpc('admin_authorize_return',{p_claim_id:id}):await supabase.from('claims').update({status,resolved_at:new Date().toISOString()}).eq('id',id);error?alert(error.message):refresh()}
 const cards=[['Pedidos activos',p.orders.length],['Pagos por revisar',p.payments.filter(x=>!['paid','refunded'].includes(x.status)).length],['Envíos activos',p.shipments.filter(x=>!['delivered','cancelled'].includes(x.status)).length],['Reclamaciones',p.claims.length],['Marcas por revisar',p.suggestions.length],['Solicitudes ARCO',p.arco.length]];
 return <div className="admin-operations">
  <section className="admin-stat-grid">{cards.map(([label,count])=><div className="admin-stat" key={String(label)}><strong>{count}</strong><span>{label}</span></div>)}</section>
  <section className="panel"><div className="admin-title"><div><h2>Usuarias</h2><p className="muted">Vista compacta de las últimas cuentas registradas.</p></div><button className="btn btn-secondary" onClick={()=>csvDownload('usuarios.csv',p.users)}>Exportar</button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Usuaria</th><th>Estado</th><th>Registro</th><th>Acción</th></tr></thead><tbody>{p.users.slice(0,10).map(u=><tr key={u.id}><td>{u.full_name||'Sin nombre'}</td><td><span className="badge">{u.is_blocked?'Bloqueada':'Activa'}</span></td><td>{u.created_at?new Date(u.created_at).toLocaleDateString('es-MX'):'No disponible'}</td><td><button className="table-action" onClick={()=>block(u)}>{u.is_blocked?'Desbloquear':'Bloquear'}</button></td></tr>)}</tbody></table></div></section>
  <div className="admin-module-grid">
   <section className="panel"><h2>Pedidos recientes</h2>{p.orders.slice(0,6).map(o=><Link className="admin-mini-row" key={o.id} href={`/pedidos/${o.id}`}><span>{o.public_code||`Pedido ${o.id.slice(0,8)}`}</span><span className="badge">{o.status}</span><strong>${Number(o.total_mxn??0).toLocaleString('es-MX')}</strong></Link>)}{!p.orders.length&&<p className="muted">Sin pedidos.</p>}</section>
   <section className="panel"><h2>Envíos</h2>{p.shipments.slice(0,6).map(s=><div className="admin-mini-row" key={s.id}><span>{s.carrier||'Paquetería pendiente'}</span><span className="badge">{s.status}</span><small>{s.tracking_number||'Sin guía'}</small></div>)}{!p.shipments.length&&<p className="muted">Sin envíos.</p>}</section>
  </div>
  <div className="admin-module-grid">
   <section className="panel"><h2>Marcas por revisar</h2>{p.suggestions.map(s=><div className="admin-compact-item" key={s.id}><strong>{s.suggested_name}</strong><select value={link[s.id]||''} onChange={e=>setLink(x=>({...x,[s.id]:e.target.value}))}><option value="">Vincular a existente</option>{p.brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><div className="actions"><button className="btn btn-primary" onClick={()=>brand(s.id,'approve_new')}>Aprobar nueva</button><button className="btn btn-secondary" disabled={!link[s.id]} onClick={()=>brand(s.id,'link_existing')}>Vincular</button><button className="btn btn-secondary" onClick={()=>brand(s.id,'reject')}>Rechazar</button></div></div>)}{!p.suggestions.length&&<p className="muted">Nada pendiente.</p>}</section>
   <section className="panel"><h2>Identidad</h2>{p.verifications.map(v=><div className="admin-compact-item" key={v.id}><strong>{v.legal_name||'Nombre no disponible'}</strong><span className="badge">{v.status}</span><div className="actions"><button className="btn btn-primary" onClick={()=>verify(v.id,'verified')}>Verificar</button><button className="btn btn-secondary" onClick={()=>verify(v.id,'rejected')}>Rechazar</button></div></div>)}{!p.verifications.length&&<p className="muted">Nada pendiente.</p>}</section>
  </div>
  <section className="panel"><h2>Reclamaciones</h2>{p.claims.map(c=><div className="admin-compact-item" key={c.id}><strong>{c.reason}</strong><p>{c.description}</p><span className="badge">{c.status}</span><div className="actions"><button className="btn btn-primary" onClick={()=>claim(c.id,'approved_return')}>Autorizar devolución</button><button className="btn btn-secondary" onClick={()=>claim(c.id,'rejected')}>Rechazar</button></div></div>)}{!p.claims.length&&<p className="muted">Sin reclamaciones abiertas.</p>}</section>
  <div className="admin-module-grid"><section className="panel"><h2>Reportes</h2>{p.reports.map(r=><div className="admin-compact-item" key={r.id}><strong>{r.reason_code}</strong><p>{r.details}</p><div className="actions"><button className="btn btn-primary" onClick={()=>reportAction(r.id,'resolved')}>Resolver</button><button className="btn btn-secondary" onClick={()=>reportAction(r.id,'dismissed')}>Descartar</button></div></div>)}{!p.reports.length&&<p className="muted">Sin reportes abiertos.</p>}</section><section className="panel"><div className="admin-title"><h2>Solicitudes ARCO</h2><button className="btn btn-secondary" onClick={()=>csvDownload('solicitudes-arco.csv',p.arco)}>Exportar</button></div>{p.arco.map(r=><div className="admin-compact-item" key={r.id}><strong>{r.request_type}</strong><p>{r.description}</p><span className="badge">{r.status}</span><div className="actions"><button className="btn btn-primary" onClick={()=>arcoAction(r.id,'resolved')}>Resolver</button><button className="btn btn-secondary" onClick={()=>arcoAction(r.id,'needs_information')}>Pedir información</button></div></div>)}{!p.arco.length&&<p className="muted">Sin solicitudes pendientes.</p>}</section></div>
 </div>}
