"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Conv={id:string;dress_id:string;buyer_id:string;seller_id:string;buyer_name?:string;seller_name?:string;last_message_at:string;dresses?:any;messages?:any[];offers?:any[];orders?:any[]};
function cleanModel(v:any){const s=String(v??"").trim();return /^(na|n\/?a|no aplica|sin modelo)$/i.test(s)?"":s}
function dressTitle(d:any){return [d?.brands?.name,cleanModel(d?.model)].filter(Boolean).join(" ")||"Vestido"}
function money(v:any){return `$${Number(v??0).toLocaleString("es-MX")} MXN`}
const STATUS:Record<string,string>={pending:"Pendiente",accepted:"Aceptada",declined:"Rechazada",expired:"Vencida",awaiting_payment:"Pendiente de pago",payment_processing:"Procesando pago",paid:"Pago confirmado",preparing_shipment:"Preparando envío",shipped:"Enviado",inspection:"Periodo de protección",completed:"Completado",cancelled:"Cancelado"};

export default function MessagesClient({initial,userId,initialActive}:{initial:Conv[];userId:string;initialActive?:string}){
 const supabase=useMemo(()=>createClient(),[]); const router=useRouter();
 const [convs,setConvs]=useState(initial);
 const first=initial.find(c=>c.id===initialActive)?.id??initial[0]?.id??"";
 const [active,setActive]=useState(first);
 const activeConv=convs.find(c=>c.id===active);
 const [messages,setMessages]=useState<any[]>(activeConv?.messages??[]);
 const [body,setBody]=useState(""); const [offerOpen,setOfferOpen]=useState(false); const [offerAmount,setOfferAmount]=useState(""); const [offerNote,setOfferNote]=useState(""); const [counter,setCounter]=useState<Record<string,string>>({}); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function refreshConversation(){router.refresh()}
 async function load(id:string){setActive(id);setError("");const {data}=await supabase.from("messages").select("id,sender_id,body,created_at,read_at").eq("conversation_id",id).order("created_at");setMessages(data??[]);await supabase.rpc("mark_conversation_read",{p_conversation_id:id})}
 async function send(){const text=body.trim();if(!text||!active)return; const {data,error}=await supabase.from("messages").insert({conversation_id:active,sender_id:userId,body:text}).select().single();if(error){setError(error.message);return}if(data){setMessages(m=>[...m,data]);setBody("")}}
 async function createOffer(){if(!activeConv)return;const amount=Number(offerAmount);if(!amount||amount<=0)return;setBusy(true);setError("");const {error}=await supabase.rpc("create_offer",{p_dress_id:activeConv.dress_id,p_amount_mxn:amount,p_conversation_id:activeConv.id,p_note:offerNote.trim()||null});setBusy(false);if(error)setError(error.message);else{setOfferOpen(false);setOfferAmount("");setOfferNote("");refreshConversation()}}
 async function offerAction(id:string,action:"accept"|"decline"|"counter"){setBusy(true);setError("");let res:any;if(action==="accept")res=await supabase.rpc("accept_offer",{p_offer_id:id});else if(action==="decline")res=await supabase.rpc("decline_offer",{p_offer_id:id});else res=await supabase.rpc("counter_offer",{p_offer_id:id,p_amount_mxn:Number(counter[id]),p_note:null});setBusy(false);if(res.error)setError(res.error.message);else if(action==="accept"&&res.data){router.push(`/pedidos/${res.data}`);router.refresh()}else refreshConversation()}
 useEffect(()=>{if(!active)return;const ch=supabase.channel(`messages:${active}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${active}`},p=>{const row=p.new as any;setMessages(m=>m.some(x=>x.id===row.id)?m:[...m,row])}).subscribe();return()=>{supabase.removeChannel(ch)}},[active,supabase]);
 const timeline=useMemo(()=>{if(!activeConv)return[];const items:any[]=[];(messages??[]).forEach(m=>items.push({kind:"message",at:m.created_at,data:m}));(activeConv.offers??[]).forEach(o=>items.push({kind:"offer",at:o.created_at,data:o}));(activeConv.orders??[]).forEach(o=>{items.push({kind:"order",at:o.created_at,data:o});if(o.shipping_quote_set_at)items.push({kind:"shipping",at:o.shipping_quote_set_at,data:o})});return items.sort((a,b)=>String(a.at).localeCompare(String(b.at)))},[activeConv,messages]);
 const canOffer=activeConv?.buyer_id===userId && activeConv?.dresses?.precio_venta_mxn;
 return <div className="messaging">
  <aside>{convs.map(c=>{const other=c.buyer_id===userId?c.seller_name:c.buyer_name;return <button key={c.id} className={active===c.id?"active":""} onClick={()=>load(c.id)}><strong>{dressTitle(c.dresses)}</strong><span className="conversation-meta">Con {other||"Usuaria"}</span><span>{new Date(c.last_message_at).toLocaleDateString("es-MX")}</span></button>})}</aside>
  <section className="chat panel">{activeConv?<>
    <div className="chat-dress-header"><div><span className="muted">Conversación sobre</span><h2><Link href={`/vestidos/${activeConv.dress_id}`} target="_blank" rel="noopener noreferrer">{dressTitle(activeConv.dresses)}</Link></h2>{activeConv.dresses?.precio_venta_mxn&&<span>{money(activeConv.dresses.precio_venta_mxn)}</span>}<div className="chat-party-line"><span><strong>Vendedora:</strong> {activeConv.seller_name||"Vendedora"}</span><span><strong>Compradora:</strong> {activeConv.buyer_name||"Compradora"}</span></div></div><Link className="btn btn-secondary" href={`/vestidos/${activeConv.dress_id}`} target="_blank" rel="noopener noreferrer">Ver vestido</Link></div>
    <div className="safety-callout"><strong>Mantén todo dentro de SECOND VOW.</strong><span>No recomendamos reunirse en persona ni realizar pagos o acuerdos fuera de la plataforma. El historial del chat, ofertas y pedidos es importante si existe una reclamación.</span></div>
    {activeConv?.seller_id===userId&&<div className="alert-info">Antes de aceptar una oferta: SECOND VOW retiene 18% del precio del vestido. Esa comisión ya incluye Stripe; recibirás 82% del vestido más el envío cotizado.</div>}
    <div className="messages">{timeline.map((item:any)=>{if(item.kind==="message"){const m=item.data;return <div key={`m-${m.id}`} className={m.sender_id===userId?"bubble mine":"bubble"}>{m.body}<small>{new Date(m.created_at).toLocaleString("es-MX")}</small></div>}
      if(item.kind==="offer"){const o=item.data;const canRespond=o.status==="pending"&&o.created_by!==userId;return <div key={`o-${o.id}`} className="commerce-event"><div className="commerce-event-label">{o.parent_offer_id?"Contraoferta":"Oferta"}</div><strong>{money(o.amount_mxn)}</strong><span className="badge">{STATUS[o.status]||o.status}</span>{o.note&&<p>{o.note}</p>}<small>Vence {new Date(o.expires_at).toLocaleString("es-MX")}</small>{canRespond&&<div className="commerce-actions"><button className="btn btn-primary" disabled={busy} onClick={()=>offerAction(o.id,"accept")}>Aceptar</button><button className="btn btn-secondary" disabled={busy} onClick={()=>offerAction(o.id,"decline")}>Rechazar</button><label className="compact-amount"><span>Contraoferta</span><input type="number" min="1" value={counter[o.id]??""} onChange={e=>setCounter(v=>({...v,[o.id]:e.target.value}))} placeholder="Monto MXN"/></label><button className="btn btn-secondary" disabled={busy||!counter[o.id]} onClick={()=>offerAction(o.id,"counter")}>Enviar contraoferta</button></div>}</div>}
      if(item.kind==="order"){const o=item.data;return <div key={`ord-${o.id}`} className="commerce-event order-event"><div className="commerce-event-label">Pedido creado</div><strong>{money(o.subtotal_mxn)}</strong><span className="badge">{STATUS[o.status]||o.status}</span><Link href={`/pedidos/${o.id}`}>Abrir pedido</Link></div>}
      const o=item.data;return <div key={`ship-${o.id}`} className="commerce-event shipping-event"><div className="commerce-event-label">Envío cotizado</div><strong>{money(o.shipping_mxn)}</strong>{o.shipping_carrier_declared&&<span>{o.shipping_carrier_declared}</span>}<p>Total de la operación: {money(o.total_mxn)}</p><Link href={`/pedidos/${o.id}`}>Continuar en el pedido</Link></div>})}</div>
    {error&&<div className="alert-error">{error}</div>}
    {canOffer&&<div className="chat-offer-box">{!offerOpen?<button className="btn btn-secondary" onClick={()=>setOfferOpen(true)}>Hacer oferta</button>:<div className="offer-compose"><label><span>Monto de la oferta (MXN)</span><input type="number" min="1" max={activeConv.dresses.precio_venta_mxn} value={offerAmount} onChange={e=>setOfferAmount(e.target.value)} placeholder="Ej. 18000"/></label><label><span>Mensaje opcional</span><input value={offerNote} maxLength={500} onChange={e=>setOfferNote(e.target.value)} placeholder="Ej. ¿Aceptarías esta cantidad?"/></label><div className="actions"><button className="btn btn-primary" disabled={busy||!offerAmount} onClick={createOffer}>Enviar oferta</button><button className="btn btn-secondary" onClick={()=>setOfferOpen(false)}>Cancelar</button></div></div>}</div>}
    <div className="composer"><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={2000} placeholder="Escribe un mensaje"/><button className="btn btn-primary" onClick={send}>Enviar</button></div>
  </>:<p>Selecciona una conversación.</p>}</section>
 </div>
}
